version: '3.9'

services:

  backend:

    build:
      context: .

    container_name: marketmix_backend

    ports:
      - "8000:8000"

  frontend:

    build:
      context: .
      dockerfile: streamlit_app/Dockerfile

    container_name: marketmix_frontend

    ports:
      - "8501:8501"

    depends_on:
      - backend